### ISSUE TITLE
Create user flow for frontend and backend

### ISSUE THREAD

**Issue by vkassingh** [Ayush-projects/chords#1]
hi @Ayush-projects , 
i would like to contirbute to the project as part of gssoc21. Do we have a group for the discussions?

**Comment by Ayush-projects** [comment]
Will be sharing workflow for both frontend and backend by tomorrow, we are starting everything from scratch and will be adding each of the functionality as a feature. Once we are sure about the contributors, we would be discussing stuffs in the group. 
Reach out to me - kryptonites.ju@gmail.com

**Comment by medhavibasera** [comment]
I would like to work on this project, I am GSSOC 2021 participant.

**Comment by wajeehamushtaq** [comment]
I am also a GSSOC participant and I would like to contribute to this project as well.

**Comment by nabin-nath** [comment]
Hello
I am Nabin Nath and also a GSSOC participant, I would really like to learn and contribute to this project.

**Comment by Shivam-Shandilya1** [comment]
Hey!! I am GSSOC participant and I want to give assisstance to your nice idea-project.Can I work on it?

**Comment by rubyruins** [comment]
Hi, I would love to contribute to this project during GSSOC 21. Would like to be a part of the discussion and contribute to the project.

**Comment by amanjha21** [comment]
Hi, I am also a GSSOC'21 participant and I would like to contribute to this project as well.

**Comment by Arshanshagarwal** [comment]
Hi, I would love to contribute and be part of this project during GSSOC21

**Comment by sahildotexe** [comment]
Hey !! I'm a participant of GSSOC'21 and I would love to contribute to this project

**Comment by MukulKolpe** [comment]
Hey!! I like the idea behind this project. I would love to contribute here as a GSSOC participant. Looking forward to knowing the workflow of this project. @Ayush-projects

**Comment by Ayush-projects** [comment]
Hey guys, I would be discussing about development of the features and workflow in our dedicated discord server after tomorrow. For now we have our logos in different sizes, we would be adding new features and doing everything from scratch, so that we get to learn about various stuffs while we will be developing this project in the interval of 3 months.

**Comment by Ayush-projects** [comment]
If you are new in open source contribution, please refer the link in the readme file, it has all the info and steps for open source contribution. I would be publishing instructions particularly for this project tomorrow.
Hoping we would be doing miracles with this project :)

**Comment by AakankshaShah** [comment]
This seems like a  very interesting and learning project.I would like to contribute to it under GSSOC'21.

**Comment by Fab-Gaurav** [comment]
As a participant of GSSOC'21 I'm interested in contributing to the project 
@Ayush-projects

**Comment by RenuPrajapati07** [comment]
Hey! I like the concept of the project and I would love to contribute to this project as a participant of GSSOC 21.

**Comment by Sushi22** [comment]
Hello there. I am a participant in GSSOC'21. I liked your project idea and I would like to contribute to this project.

**Comment by Ayush-projects** [comment]
The Front End flow chart is there in the table of the content section, if somebody is willing to write the documentation, he can start a new issue and can proceed.

**Comment by rubyruins** [comment]
> The Front End flow chart is there in the table of the content section, if somebody is willing to write the documentation, he can start a new issue and can proceed.

Would like to take this up. Could you assign it to me please? Also, is there any specific format / guidelines to write the docs? If so, could you please share?

**Comment by MukulKolpe** [comment]
Hey @Ayush-projects, should I try to work on this???

**Comment by Priyanka7011** [comment]
Hey ! I am a GSSOC 2021 participant.
I would love to work on this project .I am really excited for this.
how can I join the discord server?? @Ayush-projects

**Comment by Ayush-projects** [comment]
You can join the newly created discord server for the contributors without mentors by following this link - https://discord.gg/xgEGw54e


Discord channel with mentors would be available to you after some time in the gssoc 21 common server.
