### ISSUE TITLE
Add tensorflow logo in Readme #gssoc21 

### ISSUE THREAD

**Issue by Ayush-projects** [Ayush-projects/chords#12]

**Comment by anu-cn** [comment]
Can I work on this issue?
I am a participant of gssoc21.

**Comment by Ayush-projects** [comment]
Yes, sure.

**Comment by anu-cn** [comment]
Can you please give me a little detail about the size of the logo you want and the specific position the logo should be at.
And do you want the word "Tensor Flow" written with the logo or not?
If you have any other specifications kindly convey it to me.

Thank you.

**Comment by Ayush-projects** [comment]
Look over the readme file, all the logos are imported via CDN links, follow the same for the TensorFlow logo.
