### ISSUE TITLE
Adding contact us button

### ISSUE THREAD

**Issue by shefali12-ab** [Ayush-projects/chords#25]
Hey, I am one of participant of GSSOC'21. I would like to contribute by adding Contact Us button. 
please assign me this issue.
Thank you.

**Comment by Ayush-projects** [comment]
Assigned :)

**Comment by shefali12-ab** [comment]
> Assigned :)

Thank you for assigining  :))

**Comment by richakumari19** [comment]
Hey , I am participant in GSSOC'21. Can you please assign this to me?
