### ISSUE TITLE
Security of website - gssoc'21

### ISSUE THREAD

**Issue by krishna-y2000** [Ayush-projects/chords#52]
### Feature request:
Setting various HTTP headers using helmet for enhancing security .
Rate limiter so the server won't get overload.

Please assign this issue as part of gssoc'21.
Set the right tag level and gssoc'21 tag .

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Ayush-projects** [comment]
Yeh, Assigned.
