### ISSUE TITLE
[Need] Workflow for gssoc21 auto label

### ISSUE THREAD

**Issue by Aryamanz29** [Ayush-projects/chords#53]
### Feature request:
I want to add workflow which automatically adds `GSSOC21` label to new issues if they have  labels-synonyms: `'{"GSSOC21":["GSSOC","GSSOC21","gssoc","Gssoc","GSSoC"]}'`  in their `issue body`

![Screenshot from 2021-03-17 15-52-45](https://user-images.githubusercontent.com/56113566/111453959-209dd680-873a-11eb-93ca-37161f201192.png)

### Is your feature request related to a problem? Please describe. (optional):
Yes it solves `gssoc` label issue which every time the maintainer has to do it manually

### Describe the solution you'd like:
Using github actions this problem can be solved

<hr/>

**Note:**
* If you want to work on an issue, you should check if it has already been assigned to anyone.

**Comment by Ayush-projects** [comment]
Yeh, Assigned.

**Comment by Aryamanz29** [comment]
Kindly review my PR @Ayush-projects

**Comment by Aryamanz29** [comment]
I have check this workflow  by making new issue and its not working as expected  because you have already made an issue using the `gssoc21` label instead of `GSSOC21` so i have made changes in my PR , Kindly review that @Ayush-projects
