### ISSUE TITLE
[Typo] Fixing HowToContribute.md 

### ISSUE THREAD

**Issue by manankohlii** [Ayush-projects/chords#55]
Hello, I'm Manan, a participant for GSSoC'21, and would like to first help in making the documentation better. Please assign me the issue!

### **Describe the bug:**
Typo in Documentation

### **To Reproduce:**
1. Go to 'Documentation' Folder
2. Click on 'HowToContribute.md'
3. Scroll down to 'Step 6' where there is a typo in the word command
4. Step 7 and 8 have indentation issues

**Comment by Ayush-projects** [comment]
Issue already resolved, please cross verify, if already there please create a new issue :)
