### ISSUE TITLE
Readme.md can be changed to better one it lacks in many ways

### ISSUE THREAD

**Issue by SAHU-01** [Ayush-projects/chords#8]
The present readme only has basic details about the project,
Its lacking in:
* browser support
* Technology Stack
* links
* Code of conduct 
* clarity on the ide to be used
* necessary installations
* Connection details
* Resources
* Instructions
* Statistics of present no of forking ,pulling,etc requests

I'd like to work on those issues!

**Comment by Ayush-projects** [comment]
Yes, you can contribute and update the corresponding fields, there is a flowchart about the workflow of frontend in the table of content, please refer it for now.

**Comment by Ayush-projects** [comment]
Can you add all this info in the readme file, we have a deadline of 2 days?

**Comment by AshuKV** [comment]
Can I work on this issue under GSSoC'21? Kindly assign it to me.
